server:
  port: 8888
spring:
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    password: ${REDIS_PASSWORD:}
    port: ${REDIS_PORT:6379}
cpolar:
  userName: ${CPOLAR_USERNAME:} # 用户名
  password: ${CPOLAR_PASSWORD:} # 密码
dingTalk:
  open: ${DINGTALK_OPEN:true} # 是否钉钉提醒
  robotToken: ${DINGTALK_ROBOTTOKEN:} # 机器人token
  keyWord: ${DINGTALK_KEYWORD:} # 机器人关键字
task-cycle:
  type: ${CYCLE_TYPE:HOUR}  # HOUR 小时 MINUTE 分钟 SECOND 秒
  length: ${CYCLE_LENGTH:1}  # 间隔多久循环
  cronExpression: ${CYCLE_CRONE:} # CRONE表达式 优先于循环任务执行
useCaffeine: ${LOCAL_CACHE:false} # 使用本地缓存存储，0使用REDIS存储